server:
  port: 8400
  servlet:
    context-path: /bhq-ius
app:
  jwtSecret: test
  tokenValidity: 28600

spring:
  application:
    name: bhq-ius
  datasource:
    url: jdbc:mysql://203.162.89.200:8806/ius
    username: bhqadmin
    password: Nsi@ansv1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: false
logging:
  level:
    org:
      hibernate:
        sql: debug
      springframework: debug