server:
  port: 8400
  servlet:
    context-path: /bhq-ius
app:
  jwtSecret: test
  tokenValidity: 1800
  adminUser: adminbhq
  moodleService:
    url: https://daotao.bhq.vn/moodle/webservice/rest/server.php
    dedicated-endpoint: https://daotao.bhq.vn/moodle/webservice/upload.php
    login-endpoint: https://daotao.bhq.vn/moodle/login/token.php?service=moodle_mobile_app
    token: ed10bf82b15919211e501da908de9857
#    token: f146a7a5f4867386906fcb52e1ec8512
spring:
  application:
    name: bhq-ius
  datasource:
    url: jdbc:mysql://10.15.200.30:3306/ius
    username: bhqadmin
    password: Nsi@ansv1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: false
logging:
  level:
    org:
      hibernate:
        sql: debug
      springframework: debug